spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fortuneteller?useSSL=false&serverTimezone=UTC
    username: root
    password: haosql
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: cn.edu.fzu.dx.ygh.workback.entity  #实体类的扫描路径
  configuration:
    map-underscore-to-camel-case: true  #自动驼峰命名映射 publish_date映射为publishDate

pagehelper:
  helperDialect: mysql  #采用什么数据库
  reasonable: true  #分页合理化
  supportMethodsArguments: true #支持Mapper接口传递分页参数
  params: count=countSql #配置count查询SQL标识